version: '3.8'

services:
  activemq:
    image: symptoma/activemq:latest
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
  service-1-api:
    build:
      context: .
      dockerfile: ./service-1-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - activemq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-rapid-king-a4fc328z-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_8yvHAKePxoJ4
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      AWS_S3_BUCKET-NAME: delta-tc-upload-data
      SPRING_CLOUD_AWS_REGION_STATIC: us-east-1
      SPRING_CLOUD_AWS_CREDENTIALS_ACCESS-KEY: AKIAT2TQV6VS3D2KGCVQ
      SPRING_CLOUD_AWS_CREDENTIALS_SECRET-KEY: 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
      SPRING_ACTIVEMQ_BROKER-URL: tcp://activemq:61616
#      SPRING_ACTIVEMQ_PACKAGES_TRUST-ALL: true
#      JOB_SUBMISSION_QUEUE: job-submission-requests
#      JOB_PERSISTENCE_QUEUE: job-persistence-notifications
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_CODE_DELTA: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JMS: DEBUG
      LOGGING_LEVEL_ORG_APACHE_ACTIVEMQ: DEBUG
  service-2-persistence:
    build:
      context: .
      dockerfile: ./service-2-persistence/Dockerfile
    depends_on:
      - activemq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-rapid-king-a4fc328z-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_8yvHAKePxoJ4
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_ACTIVEMQ_BROKER-URL: tcp://activemq:61616
#      SPRING_ACTIVEMQ_PACKAGES_TRUST-ALL: true
#      JOB_SUBMISSION_QUEUE: job-submission-requests
#      JOB_PERSISTENCE_QUEUE: job-persistence-notifications
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_CODE_DELTA: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JMS: DEBUG
      LOGGING_LEVEL_ORG_APACHE_ACTIVEMQ: DEBUG
  service-3-orchestrator:
    build:
      context: .
      dockerfile: ./service-3-orchestrator/Dockerfile
    depends_on:
        - activemq
    environment:
      SERVICE1_API_URL: http://service-1-api:8080/api/jobs/upload-to-s3
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-rapid-king-a4fc328z-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_8yvHAKePxoJ4
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_ACTIVEMQ_BROKER-URL: tcp://activemq:61616
#      SPRING_ACTIVEMQ_PACKAGES_TRUST-ALL: true
#      JOB_SUBMISSION_QUEUE: job-submission-requests
#      JOB_PERSISTENCE_QUEUE: job-persistence-notifications
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_CODE_DELTA: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JMS: DEBUG
      LOGGING_LEVEL_ORG_APACHE_ACTIVEMQ: DEBUG